### ISSUE TITLE
loading failed: load web.html

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#41] opened 2015-06-15 13:20 UTC
~~~~
0$ dao -e 'load web.html'
[[ERROR]] in file "command line codes":
  At line 1 : loading failed;
1$
~~~~
~~~~
0$ dao -e 'load web.html import html'
[[ERROR]] in file "command line codes":
  At line 1 : loading failed;
1$
~~~~

**Comment by Night-walker** [comment] 2015-06-15 15:17
Works fine for me.

**Comment by dumblob** [comment] 2015-06-19 10:03
The issue is that the `libdao_html.so` is placed into `/usr/lib/dao/modules/web/html/` instead of `/usr/lib/dao/modules/web/`.

~~~~strace
0$ pwd
/home/test
0$ strace dao -e 'load web.html'
execve("/usr/bin/dao", ["dao", "-e", "load web.html"], [/* 88 vars */]) = 0
brk(0)                                  = 0x252d000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/tls/x86_64/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls/x86_64", 0x7fffd66c1c20) = -1 ENOENT (No such file or directory)
open("/usr/lib/tls/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls", 0x7fffd66c1c20)    = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64", 0x7fffd66c1c20) = -1 ENOENT (No such file or directory)
open("/usr/lib/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20U\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1067384, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbf0cb91000
mmap(NULL, 3162456, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbf0c66c000
mprotect(0x7fbf0c76f000, 2097152, PROT_NONE) = 0
mmap(0x7fbf0c96f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x103000) = 0x7fbf0c96f000
close(3)                                = 0
open("/usr/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=14600, ...}) = 0
mmap(NULL, 2109712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbf0c468000
mprotect(0x7fbf0c46a000, 2097152, PROT_NONE) = 0
mmap(0x7fbf0c66a000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fbf0c66a000
close(3)                                = 0
open("/usr/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340`\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=142912, ...}) = 0
mmap(NULL, 2213136, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbf0c24b000
mprotect(0x7fbf0c263000, 2093056, PROT_NONE) = 0
mmap(0x7fbf0c462000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7fbf0c462000
mmap(0x7fbf0c464000, 13584, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbf0c464000
close(3)                                = 0
open("/usr/lib/libdao.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320=\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1172232, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbf0cb90000
mmap(NULL, 3274568, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbf0bf2b000
mprotect(0x7fbf0c03f000, 2093056, PROT_NONE) = 0
mmap(0x7fbf0c23e000, 45056, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x113000) = 0x7fbf0c23e000
mmap(0x7fbf0c249000, 5960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbf0c249000
close(3)                                = 0
open("/usr/lib/libreadline.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260e\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0555, st_size=350087, ...}) = 0
mmap(NULL, 2402176, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbf0bce0000
mprotect(0x7fbf0bd21000, 2097152, PROT_NONE) = 0
mmap(0x7fbf0bf21000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x41000) = 0x7fbf0bf21000
mmap(0x7fbf0bf2a000, 1920, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbf0bf2a000
close(3)                                = 0
open("/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1984880, ...}) = 0
mmap(NULL, 3813008, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbf0b93d000
mprotect(0x7fbf0bad6000, 2097152, PROT_NONE) = 0
mmap(0x7fbf0bcd6000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x199000) = 0x7fbf0bcd6000
mmap(0x7fbf0bcdc000, 16016, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbf0bcdc000
close(3)                                = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=265093, ...}) = 0
mmap(NULL, 265093, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbf0cb4f000
close(3)                                = 0
open("/usr/lib/libncursesw.so.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0P\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=411648, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbf0cb4e000
mmap(NULL, 2508816, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbf0b6d8000
mprotect(0x7fbf0b737000, 2097152, PROT_NONE) = 0
mmap(0x7fbf0b937000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5f000) = 0x7fbf0b937000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbf0cb4d000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbf0cb4c000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbf0cb4b000
arch_prctl(ARCH_SET_FS, 0x7fbf0cb4c700) = 0
mprotect(0x7fbf0bcd6000, 16384, PROT_READ) = 0
mprotect(0x7fbf0b937000, 16384, PROT_READ) = 0
mprotect(0x7fbf0bf21000, 8192, PROT_READ) = 0
mprotect(0x7fbf0c96f000, 4096, PROT_READ) = 0
mprotect(0x7fbf0c66a000, 4096, PROT_READ) = 0
mprotect(0x7fbf0c462000, 4096, PROT_READ) = 0
mprotect(0x7fbf0cb92000, 4096, PROT_READ) = 0
munmap(0x7fbf0cb4f000, 265093)          = 0
set_tid_address(0x7fbf0cb4c9d0)         = 23295
set_robust_list(0x7fbf0cb4c9e0, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7fbf0c250bb0, [], SA_RESTORER|SA_SIGINFO, 0x7fbf0c25b740}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7fbf0c250c40, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fbf0c25b740}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(0)                                  = 0x252d000
brk(0x254e000)                          = 0x254e000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=3972624, ...}) = 0
mmap(NULL, 3972624, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbf0b30e000
close(3)                                = 0
open("/usr/local/dao.conf", O_RDONLY)   = -1 ENOENT (No such file or directory)
open("./dao.conf", O_RDONLY)            = -1 ENOENT (No such file or directory)
getcwd("/home/test", 511)              = 12
stat("/usr/local/sbin/dao", 0x7fffd66c22c0) = -1 ENOENT (No such file or directory)
stat("/usr/local/bin/dao", 0x7fffd66c22c0) = -1 ENOENT (No such file or directory)
stat("/usr/bin/dao", {st_mode=S_IFREG|0755, st_size=9360, ...}) = 0
stat("/usr/bin/dao", {st_mode=S_IFREG|0755, st_size=9360, ...}) = 0
brk(0x256f000)                          = 0x256f000
stat("/usr/local/lib/dao/modules/libdao_aux.so", 0x7fffd66c22c0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/dao/modules/libdao_aux.so", {st_mode=S_IFREG|0755, st_size=23176, ...}) = 0
stat("/usr/lib/dao/modules", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/home/test/.history", O_RDONLY)  = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=4001, ...}) = 0
read(3, "x = 1 > 0\nx\nx\nio.writeln(x)\ny = "..., 4001) = 4001
close(3)                                = 0
brk(0x2590000)                          = 0x2590000
rt_sigaction(SIGINT, {0x40126d, [INT], SA_RESTORER|SA_RESTART, 0x7fbf0b970540}, {SIG_DFL, [], 0}, 8) = 0
stat("/@/web/html.dac", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dac", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dac", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dac", 0x7fffd66c1fd0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/dao/modules/web/html.dac", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("web/html.dac", 0x7fffd66c2040)    = -1 ENOENT (No such file or directory)
stat("/@/web/html.dao", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dao", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dao", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dao", 0x7fffd66c1fd0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/dao/modules/web/html.dao", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("web/html.dao", 0x7fffd66c2040)    = -1 ENOENT (No such file or directory)
stat("/@/web/libdao_html.so", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/libdao_html.so", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/libdao_html.so", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/libdao_html.so", 0x7fffd66c1fd0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/dao/modules/web/libdao_html.so", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("web/libdao_html.so", 0x7fffd66c2040) = -1 ENOENT (No such file or directory)
stat("/@/web/html", 0x7fffd66c1f90)     = -1 ENOENT (No such file or directory)
stat("/home/test/web/html", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html", 0x7fffd66c1fd0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/dao/modules/web/html", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("web/html", 0x7fffd66c2040)        = -1 ENOENT (No such file or directory)
stat("/@/web/html.dac", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dac", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dac", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dac", 0x7fffd66c1fd0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/dao/modules/web/html.dac", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("web/html.dac", 0x7fffd66c2040)    = -1 ENOENT (No such file or directory)
stat("/@/web/html.dao", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dao", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dao", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html.dao", 0x7fffd66c1fd0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/dao/modules/web/html.dao", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("web/html.dao", 0x7fffd66c2040)    = -1 ENOENT (No such file or directory)
stat("/@/web/libdao_html.so", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/libdao_html.so", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/libdao_html.so", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/libdao_html.so", 0x7fffd66c1fd0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/dao/modules/web/libdao_html.so", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("web/libdao_html.so", 0x7fffd66c2040) = -1 ENOENT (No such file or directory)
stat("/@/web/html", 0x7fffd66c1f90)     = -1 ENOENT (No such file or directory)
stat("/home/test/web/html", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html", 0x7fffd66c1f90) = -1 ENOENT (No such file or directory)
stat("/home/test/web/html", 0x7fffd66c1fd0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/dao/modules/web/html", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("web/html", 0x7fffd66c2040)        = -1 ENOENT (No such file or directory)
write(2, "[[ERROR]]", 9[[ERROR]])                = 9
write(2, " in file \"", 10 in file ")             = 10
write(2, "command line codes", 18command line codes)      = 18
write(2, "\":\n", 3":
)                    = 3
write(2, "  At line ", 10  At line )              = 10
write(2, "1", 11)                        = 1
write(2, " : ", 3 : )                      = 3
write(2, "loading failed", 14loading failed)          = 14
write(2, ";\n", 2;
)                      = 2
rename("/home/test/.history", "/home/test/.history-") = 0
open("/home/test/.history", O_WRONLY|O_CREAT|O_TRUNC, 0600) = 3
write(3, "x = 1 > 0\nx\nx\nio.writeln(x)\ny = "..., 4001) = 4001
close(3)                                = 0
unlink("/home/test/.history-")         = 0
close(2)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
~~~~

**Comment by Night-walker** [comment] 2015-06-19 10:27
This issue affected the entire `web` module group. Supposedly fixed (albeit it might be a daomake issue rather then a configuration mistake).

**Comment by Night-walker** [comment] 2015-06-26 17:18
I think the issue is solved. Closing.

**Closed by Night-walker** 2015-06-26 17:18 UTC
